### ISSUE TITLE
kernel module not found "xts"

### ISSUE THREAD

**Issue by arkhan** [rakino/Rosenthal#7]
Greetings, with the last Commit when updating the kernel gives the following error:

![image](https://user-images.githubusercontent.com/3141865/214622773-4ab1d945-1680-487c-8002-b5b562c7480a.png)

Thanks

**Comment by rakino** [comment]
`CONFIG_CRYPTO_XTS=y`, xts support is built into the kernel (instead of a module), you can use something like `(delete '("xts") %base-initrd-modules)` in the `initrd-modules` field of operating-system definition to workaround this.  

I'll update the package soon (maybe half day later, as it's midnight at my place ATM.)

**Comment by rakino** [comment]
It should be fixed by a7f3db40a7aa94bb80505288b79b008752d061ac.
